version: '3.8' # Specify the version of Docker Compose

services:
  app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile if it's named differently
    ports:
      - '3000:3000' # Map port 3000 on the host to port 3000 on the container
    environment:
      NODE_ENV: production # Set environment variables as needed
    volumes:
      - .:/app # Optional: mount the current directory to the /app directory in the container
    command: npm run dev
  test:
    build: .
    command: npm run test
